"""agregar_campo_motivo_a_documentos

Revision ID: 39192f4f5dd7
Revises: e195e940e578
Create Date: 2025-06-17 22:37:16.831407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39192f4f5dd7'
down_revision = 'e195e940e578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_column('motivo')

    # ### end Alembic commands ###
