"""Agregar is_verified a Usuario

Revision ID: 479e0f06a242
Revises: 6bc374b8edf6
Create Date: 2025-06-02 10:46:07.247312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479e0f06a242'
down_revision = '6bc374b8edf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
