"""Inicial

Revision ID: 6bc374b8edf6
Revises: 
Create Date: 2025-06-02 00:47:51.775120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc374b8edf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('clave_publica', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('condominios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_admin'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('condominio_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_union', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_condominio', 'id_usuario')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_emisor', sa.Integer(), nullable=False),
    sa.Column('id_condominio', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=50), nullable=True),
    sa.Column('ruta_archivo_cifrado', sa.String(length=300), nullable=True),
    sa.Column('nonce', sa.LargeBinary(), nullable=True),
    sa.Column('tag', sa.LargeBinary(), nullable=True),
    sa.Column('firma_emisor', sa.LargeBinary(), nullable=True),
    sa.Column('firma_admin', sa.LargeBinary(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_condominio'], ['condominios.id'], ),
    sa.ForeignKeyConstraint(['id_emisor'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documentos')
    op.drop_table('condominio_usuarios')
    op.drop_table('condominios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
