"""Cambios para asociaciones entre tablas

Revision ID: 9d6d8e1d4b23
Revises: f41b65898ed0
Create Date: 2025-06-16 21:44:29.928298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d6d8e1d4b23'
down_revision = 'f41b65898ed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), nullable=True))
        batch_op.alter_column('id_admin',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('tipo_documento',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
        batch_op.alter_column('contenido_cifrado',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('nonce',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('tag',
               existing_type=sa.BLOB(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('tag',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('nonce',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('contenido_cifrado',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('tipo_documento',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=True)

    with op.batch_alter_table('condominios', schema=None) as batch_op:
        batch_op.alter_column('id_admin',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
