"""Documento: pasar ruta a BLOB contenido_cifrado

Revision ID: f41b65898ed0
Revises: 479e0f06a242
Create Date: 2025-06-08 02:39:34.509507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f41b65898ed0'
down_revision = '479e0f06a242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido_cifrado', sa.LargeBinary(), nullable=False))
        batch_op.alter_column('nonce',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.alter_column('tag',
               existing_type=sa.BLOB(),
               nullable=False)
        batch_op.drop_column('ruta_archivo_cifrado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_archivo_cifrado', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=True))
        batch_op.alter_column('tag',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.alter_column('nonce',
               existing_type=sa.BLOB(),
               nullable=True)
        batch_op.drop_column('contenido_cifrado')

    # ### end Alembic commands ###
